module.exports = {
  darkMode: 'class',
  content: ['./static/index.html', './static/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        outline: '#859582',
        'inverse-surface': '#e0e2e6',
        primary: '#43fe6d',
        'on-secondary-fixed-variant': '#723600',
        'secondary-fixed': '#ffdcc7',
        'on-secondary-container': '#5e2b00',
        'secondary-container': '#ff8000',
        'surface-container-high': '#272a2d',
        'surface-tint': '#15e558',
        'inverse-primary': '#006e25',
        'on-primary-container': '#005d1e',
        'tertiary-container': '#6ccdff',
        'on-surface-variant': '#bacbb6',
        'primary-fixed-dim': '#15e558',
        'on-tertiary-container': '#005675',
        'on-primary': '#00390f',
        'tertiary-fixed': '#c3e8ff',
        surface: '#101417',
        'surface-dim': '#101417',
        'on-surface': '#e0e2e6',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#ffb787',
        'surface-container': '#1d2023',
        secondary: '#ffb787',
        'primary-container': '#00e054',
        'on-primary-fixed-variant': '#00531a',
        'inverse-on-surface': '#2d3134',
        'tertiary-fixed-dim': '#7ad0ff',
        'on-tertiary-fixed-variant': '#004c69',
        'outline-variant': '#3c4b3a',
        'surface-bright': '#363a3d',
        'surface-container-low': '#191c1f',
        'on-secondary-fixed': '#311300',
        'on-primary-fixed': '#002106',
        'on-secondary': '#502400',
        'on-error': '#690005',
        'on-tertiary-fixed': '#001e2c',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0b0f11',
        'on-tertiary': '#003549',
        'surface-variant': '#323538',
        tertiary: '#b9e4ff',
        background: '#101417',
        'on-background': '#e0e2e6',
        'primary-fixed': '#6cff80',
        'surface-container-highest': '#323538',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'stack-sm': '8px', 'stack-lg': '32px', gutter: '24px',
        'margin-desktop': '48px', 'margin-mobile': '16px', unit: '4px', 'stack-md': '16px',
      },
      fontFamily: {
        'headline-lg': ['Space Grotesk', 'Geist'],
        'headline-lg-mobile': ['Space Grotesk', 'Geist'],
        'label-md': ['Space Grotesk', 'Geist'],
        'headline-md': ['Space Grotesk', 'Geist'],
        'body-md': ['Geist'],
        'label-sm': ['Space Grotesk', 'Geist'],
        'display-lg': ['Space Grotesk', 'Geist'],
        'body-lg': ['Geist'],
      },
      fontSize: {
        'headline-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '1.35', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '1', letterSpacing: '0.06em', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
      },
    },
  },
};
